<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLayer\DomainLayer.csproj">
      <Private>True</Private>
    </ProjectReference>
    <ProjectReference Include="..\InfrastructureLayer\InfrastructureLayer.csproj">
      <Private>True</Private>
    </ProjectReference>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<!-- Pinned to override transitive dep with CVE-2026-26127 -->
		<PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.14" />
	</ItemGroup>

</Project>
